### ISSUE TITLE
Automatically Build Solution before Start and Debug

### ISSUE THREAD

**Issue by van800** [JetBrains/godot-support#16]
Currently it is missing for some reason

**Comment by ForNeVeR** [comment]
In Rider 2020.2, you'll be able to implement a `com.jetbrains.rider.build.tasks.SolutionRunConfiguration` marker interface in your run configuration, and it will automatically get the corersponding before-launch task.

**Comment by jvidalv** [comment]
@ForNeVeR Can you explain how do you do that?

**Comment by ForNeVeR** [comment]
Just add `com.jetbrains.rider.build.tasks.SolutionRunConfiguration` to the list of interfaces implemented by `GodotDebugRunConfiguration`.

(Please note that this interface is only available in Rider 2020.2, and the plugin, as I can see, still targets Rider 2020.1, so this may be impossible to do at the moment without bumping the Rider version – which may be problematic, since there're no publicly available Rider builds from 2020.2 (yet).)

**Comment by van800** [comment]
fixed in plugin .36, which targets 2020.2 EAP5+
