### ISSUE TITLE
Type 'Godot.SignalAwaiter' is not awaitable

### ISSUE THREAD

**Issue by knightofiam** [JetBrains/godot-support#67]
### Issue description

Use of the `await` keyword in an async method in C# eventually leads to the error on `await` keyword: `Type 'Godot.SignalAwaiter' is not awaitable`.

The only (temporary) workaround I've found is restarting Rider.

The error appears intermittently and does not cause any compilation or runtime errors; it only occurs during IDE code analysis but it's obviously an issue if every code file using await is flagged as having broken code.

We determined [here](https://github.com/godotengine/godot/issues/52594#issuecomment-917770209) that this is not a bug in Godot but most likely in Rider. And the most likely culprit being the Godot Support plugin - although it's still unclear whether it's the plugin or Rider itself, but this plugin seems to be the most likely place to report this after starting with Godot itself.

### Steps to reproduce

1. Create a C# async method using the `await` keyword in JetBrains Rider, e.g.:

```
using Godot;

public class Test : Node2D
{
  private async void TestAwait() => await ToSignal (GetTree().CreateTimer (1, false), "timeout");
}
```

2. Eventually, you will receive an error in the IDE on the `await` keyword: `Type 'Godot.SignalAwaiter' is not awaitable`:

![await-error](https://user-images.githubusercontent.com/72765293/133034299-05e5e9ad-e583-4417-baca-24005cd9f593.png)

You can also see that I've attempted to disable the `ConfigureAwait` analysis, and although it is disabled, the error persists:

![configure-await-disabled](https://user-images.githubusercontent.com/72765293/133034459-3a95a63b-e8aa-4616-a17c-7395d43777bd.png)

### System information

- JetBrains Rider 2021.2
- Godot Support Plugin 2021.2.77
- Godot 3.3.2.stable.mono
- MacOS 11.4 (Big Sur)
- .NET 5.0.302
- MSBuild 16.0
- Mono 6.12.0.122

csproj:
```
<Project Sdk="Godot.NET.Sdk/3.3.0">
    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>9.0</LangVersion>
    </PropertyGroup>
</Project>
```

### Minimal reproduction project

Note: Please keep in mind that the issue occurs intermittently so it may not be fully reproducible by the test project provided here. This setup simply provides an opportunity for the bug to possibly occur. I have not yet determined the trigger.

[test.zip](https://github.com/JetBrains/godot-support/files/7151504/test.zip)

**Comment by van800** [comment]
I don't think the issue is caused by this plugin. I have tried reproducing the problem with the minimal project, which you have provided, but no luck for now. I understand that the issue is intermittent. 
If you have some more-or-less working steps to reproduce, you may disable the plugin and see if it affects the issue.

I think, it would be more effective to report to the Rider itself. To help investigating the issue:
1. Update Rider to 2021.2.1 (latest version)
2. Once the issue reproduces - call Help | Report a Bug, agree to attach logs.

You may also try Unload-Reload project in the context menu of the project.

**Comment by van800** [comment]
I have tried to checkout the mentioned revision - the issue doesn't show up.
Also tried to get the previous revision and make the renames - doesn't reproduce.

If the issue happens again, please call **Help | Report a Bug, agree to attach logs**.

Please don't continue this discussion here, because the issue is not connected to this plugin. I mean, it would likely reproduce even with this plugin being disabled.
